name: Build libraop for all supported platforms

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    strategy:
      matrix:
        include:
          - os-arch: aarch64
            gcc-arch: aarch64-linux-gnu
          - os-arch: x86_64
            gcc-arch: x86_64-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare build environment
        run: |
          apt-get update
          apt-get install -y build-essential git make gcc g++ libssl-dev ${{ matrix.os-arch == 'aarch64' && 'gcc-aarch64-linux-gnu g++-aarch64-linux-gnu' || '' }}
          mkdir -p release

      - name: Build
        run: |
          if [ "${{ matrix.os-arch }}" = "aarch64" ]; then
            export CC=aarch64-linux-gnu-gcc
            export CXX=aarch64-linux-gnu-g++
          fi
          make HOST=linux PLATFORM=${{ matrix.os-arch }} STATIC=1 -j$(nproc) cleanlib
          chmod +x bin/cliraop-linux-${{ matrix.os-arch }}
          cp bin/cliraop-linux-${{ matrix.os-arch }} release/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cliraop-linux-${{ matrix.os-arch }}
          path: release/
